version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
jobs:
  build:
    docker:
      - image: contraktor_backend
    steps:
      - run: echo "hello world"
